## 基础依赖jdk8
FROM openjdk:8
RUN mkdir -p /home/shao_WM

WORKDIR /home/shao_WM

ARG JAR_FILE=target/shao_WM-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE}  shao_WM-0.0.1-SNAPSHOT.jar
## 端口映射
EXPOSE 8081 8081
## 时区                     # jvm 的一最小堆内存，最大堆内存
ENV TZ=Asia/Shanghai JAVA_OPTS="-Xms256m -Xmx512m"
## 睡10秒 执行 java -jar  blogserver-0.0.1-SNAPSHOT.jar 命令
CMD sleep 10; java -jar  shao_WM-0.0.1-SNAPSHOT.jar  $JAVA_OPTS
# 哪个是删除多余的镜像和容器，你不是每次项目都会构建一个镜像吗。你可以直接在idea 里面删
# images 就是镜像，， containers 就是容器 这也可以delete 停止容器之类的，你都不用用命令了

## 重新连接一下就行了
##下面这个喊不出来名字的就是多余的，旧的镜像你可以删了。上次部署的，被改名了 ，容器好像都自动删了，大概就这样
##服务器没有jar 包了，直接传的镜像了。没啥区别，以前你是在服务器打包成镜像的，现在是直接在本地打包成镜像的
##还是不要删了。因为我不知道你怎么部署的，记得给我确认收货加好评啊

## docker-compose.yaml文件创建容器是十分方便的，只用运行  docker-compose up -d
## 你用docker 创建vue 容器，很麻烦的，还要挂载啥的，我建议你还是不要用
