server:
  port: 8081

spring:
  # 邮件配置
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: AJITJHAXURTMIXDF
    username: s17357563108@163.com
    port: 25
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.1.102
    virtual-host: /
    port: 5672
    # 消息失败回调
    publisher-returns: true
    # 消息确认回调
    publisher-confirm-type: correlated
#    listener:
#      simple:
#        acknowledge-mode: manual
  application:
    name: shao_wm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shao_wm?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 200273shz
  redis:
    host: 192.168.1.102
    port: 6379
    password: 200273shz
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
  configuration:
    # mybatis-plus默认开启了下滑线转换驼峰 需要关闭（设置为false）
    map-underscore-to-camel-case: false
  type-aliases-package: com.shz.entity
#  global-config:
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 0
logging:
  level:
    com.hmdp: debug
  pattern:
    dateformat: mm:ss.SSS
OSS:
  # yourEndpoint填写Bucket所在地域对应的Endpoint。以华东1（杭州）为例，Endpoint填写为https://oss-cn-hangzhou.aliyuncs.com。
  endpoint:  
  # 阿里云账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM用户进行API访问或日常运维，请登录RAM控制台创建RAM用户。
  accessKeyId:  
  accessKeySecret:  
  # 填写Bucket名称。
  bucketName:  
  # 外网访问Bucket域名
  sufferUrl:  
  # 待存储云文件夹
  parentDir: 
alipay:
  appId:  
  appPrivateKey:  
  alipayPublicKey:  
  notifyUrl:  





