server:
  port: 8081

spring:
  # 邮件配置
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: AJITJHAXURTMIXDF
    username: s17357563108@163.com
    port: 25
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.1.102
    virtual-host: /
    port: 5672
    # 消息失败回调
    publisher-returns: true
    # 消息确认回调
    publisher-confirm-type: correlated
#    listener:
#      simple:
#        acknowledge-mode: manual
  application:
    name: shao_wm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shao_wm?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 200273shz
  redis:
    host: 192.168.1.102
    port: 6379
    password: 200273shz
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
  configuration:
    # mybatis-plus默认开启了下滑线转换驼峰 需要关闭（设置为false）
    map-underscore-to-camel-case: false
  type-aliases-package: com.shz.entity
#  global-config:
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 0
logging:
  level:
    com.hmdp: debug
  pattern:
    dateformat: mm:ss.SSS
OSS:
  # yourEndpoint填写Bucket所在地域对应的Endpoint。以华东1（杭州）为例，Endpoint填写为https://oss-cn-hangzhou.aliyuncs.com。
  endpoint: oss-cn-hangzhou.aliyuncs.com
  # 阿里云账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM用户进行API访问或日常运维，请登录RAM控制台创建RAM用户。
  accessKeyId: LTAI5tPzabw9rULKkVQE5yjP
  accessKeySecret: aP3fyxtxmrTm1NRfXB1h3VccfGtrCj
  # 填写Bucket名称。
  bucketName: shaowm
  # 外网访问Bucket域名
  sufferUrl: shaowm.oss-cn-hangzhou.aliyuncs.com
  # 待存储云文件夹
  parentDir: img
alipay:
  appId: 2021000121677073
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCv4+nht/eql9PH/B1zgZYywVeagDoOVdTFpzxTL5Enog3YZkHNVvCyiv2NrhpJLp24aHe9GtM+KpKHuhtxBk4Qk+jcsXUYI+p/ND4vBMFdWDDeJQkNjcD6PooM0koX63o9UO+DCe8fNTbl08utee1MajQoivPlhesY6jnLmnX7DSRs9gpP/PG2dTWMKfeDcRhxXKjN3feYLOoojzFK+Ov9aKbK5rydykuI8X0X+sIf5V4HBF6Vd06dQ5uTRSURlhWkLFKLjkBVTzmaPJ8bB5RbM6JbdcuM+nwEYQnMVWZ4DeQh2z03gGpb/zxZBTWloQ86KKyG8zOUBjknnWzxvGcbAgMBAAECggEAGJ25GdH5Y3KkPRTXulakgq30aLcRaPgyMwdYtfuuQPG5JlQJWYeVYCd7nNyE6UEQ6cIVH+4lKkoi/8PYG1Vaj49jw59CWAKOywawvTvZJAs3q59bSP5Rx7QA9hJoNDjMftBY9OnrAV8dM8UUeE7cGxmx+wqXX8QCRxZgyFHxuRS+OFfLsbCWGKvdGm2pJ9umlbc6PyD66zCEuEaCgxjnjJng4kCnfqEKpvBQ5tFKtO9BrLgVA3+/EORdyoQX4NRVKdzLRGjvFCf6/5JHFzY5sz0wg9CBkt37AxO+Ncporpa0zdsCZObiYM7/LbFAygRDM6+YxjEHVqpwBo6UIBTXQQKBgQDks+4aMXZPMbx0naJwGhdiapH1/0Lde65RYmOyfkMls49Ke6xqSFvjXc8eft3TcIU5uoq3LyDgVVcMnGMkyty6bQ8jITuaQjriFHAmNXoan86T/DWrJQkrXaa1CNR67zoyD2kfrUcPqWnctzqRsewb4990tpTQcv5Yu6IivFY5QwKBgQDE4kh3nR9etyFQjcS4t0FqhFdCbWKqIKQcmoneUnncBF3XOdxhUGRvUHPDNrF8+Bzb9DoxEZQZMLfJm9ca0mKNnf7JVseN7dELSD9HnrvISeI3UUQ3+v2LH4/CPmgQ6Ey8GrZvRBNqVhqQvHZkOTtWCCssQ8InhQOrsrD4vurxSQKBgQDaHJeJt35jjMV0Whne26NNouFNQIJehGP9Dd6TDkOvow2XNVd7jULFFmQ/azLXQcptAfDlPzcVe44nYsZTAn179iKnmDwlo+BQWLmUVw/6cEotbC0q6YlTKF+i66bpD1nrADN7mF/bGfDyJHThGlRZTPuBbdeC7QiRS3EXu5JnzQKBgQCLF8JSnvJ2m7IxkraUOQNCGVT8XQMDZiQLATK9mk71HTCeyQXkykLqUVA3bgBeZXsd+aDS4bRbR4vQJwUEsfVmT2SdIW3B222AJv5tvrqzeV8T7ZngYrWVACsz85rZtwPfMJAKc3G0AjiqYDrT+4rr8MFveD9GZDZ/qrJUSaz54QKBgQDaKuLu50NA0GhLcXqcJJ8T1tpv6/b8BTqqiH8Yc6TP8hAhus0N8IoYvgivqg+93ukMukCbi/diYFdCxV+CQ510taQtcAYCOmZZc7mRB8fNRcdo/nxMb24TaEWZhrMOWybR6L01D4N3vrigKjH7J+Wlj1hPnAIbVjFTLkSUcYXdOw==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuu49eZ0vLrff0+VeasjuwyU7we2zu0JEr/MhBvV6ce4+VPJTT/wzL134gUZT9K1z2L/96x2EQlM/PeF7LWZitbHey0udtq8N7Ine9ig1t5m7FP7ht0uJDHNXg8EwZj4UalLhrmVFwtYOAcrflT/74XRHLwVz6+2Dn3aJ96CwShrPRbxEHWeOffHSyysEyogArsDDu5Vc0l5Om2XB5L2TPRPCIy6jvrZurkKkRZeEPzzPQ6ghimhKYxxQdLFoKY0/U8rBlo34fCjNHfHE9GHeLF8hKTE00XehF5cfF+hsgJltpux9VZr+hMblzo3tmtVeVUAkTvnUwae7FklsAwHCEQIDAQAB
  notifyUrl: http://u3akpy.natappfree.cc/alipay/notify





